repo: "hidden-message-fixer"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 1
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true

js:
  - path: "js/main.js"
    valid: true
    bestPractices: true

screenshots:
  - path: 'index.html'
    sizes: [400]
